# Generated by Django 4.1.2 on 2022-11-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_sale_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.TextField(default='', max_length=3)),
                ('description', models.TextField(default='')),
                ('currency', models.TextField(default='', max_length=3)),
                ('net', models.FloatField()),
                ('vat', models.FloatField()),
            ],
        ),
    ]
