# Generated by Django 4.1.2 on 2022-11-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_sale_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSaleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('country', models.TextField(default='')),
                ('country_code', models.TextField(default='', max_length=3)),
                ('description', models.TextField(default='')),
                ('currency', models.TextField(default='', max_length=3)),
                ('net', models.FloatField()),
                ('vat', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='purchase_sale_data',
        ),
    ]
