# Generated by Django 4.1.2 on 2022-11-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_sale_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='purchase_sale_data',
            new_name='PurchaseSaleData',
        ),
    ]
