# Generated by Django 4.1.2 on 2022-11-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_sale_api', '0002_rename_purchase_sale_data_purchasesaledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesaledata',
            name='country_code',
            field=models.TextField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchasesaledata',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
