version: "3.7"
services:
  database:
    image: postgres:13.0
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    depends_on:
      - database
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=database
      - APP_ENVIRONMENT=docker
volumes:
  data: